spring:
  application:
    name: ims
  elasticsearch:
    rest:
      uris: http://119.23.182.173:9200
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: 888888
    username: root
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    url: jdbc:mysql://127.0.0.1:3306/ims?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 180000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      #打开druid.keepAlive之后，当连接池空闲时，池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，
      # 则会执行keepAlive操作，即执行druid.validationQuery指定的查询SQL，一般为select * from dual，
      # 只要minEvictableIdleTimeMillis设置的小于防火墙切断连接时间，就可以保证当连接空闲时自动做保活检测，不会被防火墙切断
      keep-alive: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    id-type: 0

okhttp:
  #最大连接数
  maxIdle-connections: 200
  #每个连接的生命时长(单位为秒)
  keep-alive-duration: 10
  #连接超时(单位为秒)
  connect-timeout: 5
  #读数据超时(单位为秒)
  read-timeout: 15

